### ISSUE TITLE
How do I run this?

### ISSUE THREAD

**Issue by joshdavham** [xiety/AnkiHistoryVisualization#1]
Hi there!

Just found your repo today. It looks really cool and I'd like to try it out myself. However, there's no instructions in the README or elsewhere that I can find and I don't know C#.

Would you consider adding set up instructions in the README?

**Comment by xiety** [comment]
Hi!

The code in this repository is closely related to my decks, and is intended for those who want to modify code for their own decks.

For more universal visualization I have another repository with addon for Anki here:

https://github.com/xiety/anki_history_visualizer

But if you want to run this code, then the standard `.NET Runtime 8` tool `dotnet run` is used. You can install it from here:

https://dotnet.microsoft.com/en-us/download/dotnet/8.0

You should run it from `AnkiHistoryVisualization` subfolder where `.csproj` file is located.

But it will create a visualization based on my examples configured in the [Program.cs](https://github.com/xiety/AnkiHistoryVisualization/blob/main/AnkiHistoryVisualization/Program.cs) file

**Comment by joshdavham** [comment]
Thanks for the reply!

I'll go check out that other repo then.
